/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GeneralIndexRouteImport } from './routes/general/index'

const GeneralIndexRoute = GeneralIndexRouteImport.update({
  id: '/general/',
  path: '/general/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/general/': typeof GeneralIndexRoute
}
export interface FileRoutesByTo {
  '/general': typeof GeneralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/general/': typeof GeneralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/general/'
  fileRoutesByTo: FileRoutesByTo
  to: '/general'
  id: '__root__' | '/general/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GeneralIndexRoute: typeof GeneralIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/general/': {
      id: '/general/'
      path: '/general'
      fullPath: '/general/'
      preLoaderRoute: typeof GeneralIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  GeneralIndexRoute: GeneralIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
