/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GeneralIndexRouteImport } from './routes/general/index'
import { Route as AdvancedIndexRouteImport } from './routes/advanced/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralIndexRoute = GeneralIndexRouteImport.update({
  id: '/general/',
  path: '/general/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedIndexRoute = AdvancedIndexRouteImport.update({
  id: '/advanced/',
  path: '/advanced/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof SettingsRoute
  '/advanced/': typeof AdvancedIndexRoute
  '/general/': typeof GeneralIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRoute
  '/advanced': typeof AdvancedIndexRoute
  '/general': typeof GeneralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/settings': typeof SettingsRoute
  '/advanced/': typeof AdvancedIndexRoute
  '/general/': typeof GeneralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/settings' | '/advanced/' | '/general/'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/advanced' | '/general'
  id: '__root__' | '/settings' | '/advanced/' | '/general/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SettingsRoute: typeof SettingsRoute
  AdvancedIndexRoute: typeof AdvancedIndexRoute
  GeneralIndexRoute: typeof GeneralIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general/': {
      id: '/general/'
      path: '/general'
      fullPath: '/general/'
      preLoaderRoute: typeof GeneralIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/': {
      id: '/advanced/'
      path: '/advanced'
      fullPath: '/advanced/'
      preLoaderRoute: typeof AdvancedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SettingsRoute: SettingsRoute,
  AdvancedIndexRoute: AdvancedIndexRoute,
  GeneralIndexRoute: GeneralIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
